[package]
name = "chert_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
chert_accessor = { path = "../chert_accessor" }
quote = "1.0.28"
syn = { version = "2.0.18", features = ["extra-traits", "test"] }
proc-macro2 = "1.0.60"
